apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hcp-consul-fed-demo-eu-central
  region: eu-central-1
  version: "1.18"

vpc:
  cidr: 172.27.0.0/20

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
