apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hcp-consul-fed-demo-us-west
  region: us-west-2
  version: "1.18"

vpc:
  cidr: 172.25.0.0/20

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
